Repository swaxtic/detective-multisender, pull requests merged in 2022-02, with the labels that each got.

#3 Sandy dev
  src/app/app.component.scss
  src/app/app.module.ts
  src/app/components/app-bar/app-bar.component.html
  src/app/components/app-bar/app-bar.component.scss
  src/app/components/app-bar/app-bar.component.spec.ts
  src/app/components/app-bar/app-bar.component.ts
  src/app/components/multisender-hero/multisender-hero.component.html
  src/app/components/multisender-hero/multisender-hero.component.scss
  src/app/components/multisender-hero/multisender-hero.component.spec.ts
  src/app/components/multisender-hero/multisender-hero.component.ts
  src/app/pages/main/main.component.html
  src/app/pages/main/main.component.scss
  src/app/pages/pages-routing.module.ts
  src/app/pages/pages.module.ts
  src/app/views/nft-multisender/nft-multisender.component.html
  src/app/views/token-multisender/token-multisender.component.html
  src/assets/images/svg/arrow-down.svg
  src/assets/images/svg/box.svg
  src/assets/images/svg/crown.svg
  src/assets/images/svg/dice.svg
  src/styles.scss
  tailwind.config.js
Labels: bug

#4 Sandy dev
  src/app/components/app-bar/app-bar.component.html
  src/app/components/app-bar/app-bar.component.ts
  src/app/components/multisender-hero/multisender-hero.component.html
  src/app/pages/main/main.component.html
  src/app/views/nft-multisender/nft-multisender.component.html
  src/app/views/nft-multisender/nft-multisender.component.scss
  src/app/views/nft-multisender/nft-multisender.component.ts
  src/app/views/token-multisender/token-multisender.component.html
  src/app/views/token-multisender/token-multisender.component.scss
  src/app/views/token-multisender/token-multisender.component.ts
  src/styles.scss
  tailwind.config.js
Labels: bug, enhancement

#5 Sandy dev
  src/app/components/app-bar/app-bar.component.html
  src/app/components/app-bar/app-bar.component.scss
  src/app/components/app-bar/app-bar.component.ts
  src/assets/images/networks/arbitrum.svg
  src/assets/images/networks/optimism.svg
  src/assets/images/svg/close.svg
  src/assets/images/svg/metamask.svg
  src/assets/images/svg/wallet.svg
  tailwind.config.js
Labels: enhancement

#6 Sandy dev
  src/app/components/app-bar/app-bar.component.html
  src/app/components/app-bar/app-bar.component.ts
  src/app/views/nft-multisender/nft-multisender.component.html
  src/app/views/nft-multisender/nft-multisender.component.scss
  tailwind.config.js
Labels: enhancement

#8 WIP - token multisender
  angular.json
  package.json
  src/app/components/app-bar/app-bar.component.html
  src/app/components/app-bar/app-bar.component.ts
  src/app/components/header/header.component.html
  src/app/components/header/header.component.scss
  src/app/components/header/header.component.spec.ts
  src/app/components/header/header.component.ts
  src/app/config/abi/detectiveMultisender.json
  src/app/config/abi/erc20.json
  src/app/config/constants/api-constants.ts
  src/app/config/constants/contracts.ts
  src/app/config/constants/keys.ts
  src/app/config/constants/networks.ts
  src/app/pages/pages.module.ts
  src/app/shared/local-storage-service/local-storage.service.spec.ts
  src/app/shared/local-storage-service/local-storage.service.ts
  src/app/shared/shared.module.ts
  src/app/shared/web3-service/web3.service.spec.ts
  src/app/shared/web3-service/web3.service.ts
  src/app/views/token-multisender/token-multisender.component.ts
  src/environments/environment.ts
  src/polyfills.ts
  tsconfig.json
Labels: documentation, enhancement
